version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mi-app-dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Puerto para debugging
    environment:
      - NODE_ENV=development
      - DEBUG=app:*
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_DB: myapp_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6380:6379"

  # Herramientas de desarrollo
  adminer:
    image: adminer
    container_name: adminer-dev
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_dev_data:
