apiVersion: v1
kind: ServiceAccount
metadata:
  name: mi-app-sa
  namespace: default
  labels:
    app: mi-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mi-app-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mi-app-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: mi-app-sa
  namespace: default
roleRef:
  kind: Role
  name: mi-app-role
  apiGroup: rbac.authorization.k8s.io
