apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: default
  labels:
    app: mi-app
type: Opaque
data:
  # Valores codificados en base64
  # Para generar: echo -n 'valor' | base64
  url: cG9zdGdyZXNxbDovL3Bvc3RncmVzLXNlcnZpY2U6NTQzMi9taWFwcA==
  username: bWlhcHBfdXNlcg==
  password: bWlfc3VwZXJfc2VjcmV0X3Bhc3N3b3Jk

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJtaS1yZWdpc3Ryby5jb20iOnsidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiJwYXNzIiwiYXV0aCI6ImRYTmxjanB3WVhOeiJ9fX0=

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
  labels:
    app: mi-app
type: Opaque
data:
  jwt-secret: bWlfc3VwZXJfc2VjcmV0X2p3dF9rZXk=
  api-key: bWlfYXBpX2tleV9zZWNyZXQ=
  encryption-key: bWlfZW5jcnlwdGlvbl9rZXk=
